#!/usr/bin/env bash
rootdir="$1"
prefix="$rootdir/usr"
venvdir="$prefix/share"

mkdir -p "$venvdir"
cd "$venvdir"
python3.10 -m venv yoyo-python
source yoyo-python/bin/activate

# Pip Install
python3.10 -m pip install numba

deactivate